version: "3.9"

services:
  db:
    image: postgres:14.4-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init_db.sql
  ingestor:
    image: metlo/backend      
    command: yarn start-collector
    container_name: metlo-ingestor
    depends_on:
      - cache
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - DB_URL=postgres://postgres:postgres@db:5432/metlo_api_security
  cache:
    image: redis:7.0.4
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
  backend:
    image: metlo/backend
    container_name: metlo-backend
    restart: unless-stopped
    depends_on:      
      - cache
    ports:
      - 8080:8080
    environment:
      - DB_URL=postgres://postgres:postgres@db:5432/metlo_api_security
      - REDIS_URL=redis://:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81@cache:6379
      #- ENCRYPTION_KEY=
      ###  BACKEND_URL should point to externally accessible url for ingestor  ###
      #- BACKEND_URL= 
      #- EXPRESS_SECRET=
  jobs:
    image: metlo/jobrunner
    container_name: metlo-jobs
    restart: unless-stopped
    environment:
      - DB_URL=postgres://postgres:postgres@db:5432/metlo_api_security
  frontend:
    image: metlo/frontend
    container_name: metlo-frontend
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://backend:8080
    ports:
      - 8000:3000

volumes:
  db:
    driver: local
  cache:
    driver: local
