name: build

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'frontend'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        cache-dependency-path: ./frontend/yarn.lock
        node-version: '18.x'
        cache: 'yarn'
    - name: Yarn Install Common
      run: yarn
      working-directory: 'common'
    - name: Yarn Build Common
      run: yarn build
      working-directory: 'common'
    - name: Yarn Install Frontend
      run: yarn
      working-directory: 'frontend'
    - name: Yarn Build Frontend
      run: yarn build
      working-directory: 'frontend'

  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'backend'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        cache-dependency-path: ./backend/yarn.lock
        node-version: '18.x'
        cache: 'yarn'
    - name: Yarn Install Common
      run: yarn
      working-directory: 'common'
    - name: Yarn Build Common
      run: yarn build
      working-directory: 'common'
    - name: Yarn Install Backend
      run: yarn
      working-directory: 'backend'
    - name: Yarn Build Backend
      run: yarn build
      working-directory: 'backend'